spring:
  profiles:
    active: "${ENV_SPRING_PROFILES_ACTIVE:local, security-disabled}"
  application:
    name: brp-mock-service
  jackson:
    date-format: "yyyy-MM-dd"
  security.disabled: true

logging:
  level:
    root: ""
    org.springframework.web: "debug"
    org.hibernate: "error"

server:
  port: 8080
  address: localhost

environment:
  person-folder-path: "${BRP_PERSON_FOLDER_PATH:/data/persons}"
  #Configure the default response status for ALL mock endpoints (can be overridden per request)
  global-forced-response-status: ${BRP_GLOBAL_FORCED_RESPONSE_STATUS:}
  #Configure the default response delay (in milliseconds) for ALL mock endpoints (can be overridden per request)
  global-forced-delay-ms: ${BRP_GLOBAL_FORCED_DELAY_MS:0}
---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: staging
#override other variables as needed for staging here
---
spring:
  config:
    activate:
      on-profile: ci
#override other variables as needed for ci/cd pipeline here
---
spring:
  config:
    activate:
      on-profile: acceptance
#override other variables as needed for acceptance here
---
spring:
  config:
    activate:
      on-profile: prod
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false #we don't want to expose swagger ui in production
#override other variables as needed for production here